services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce_db
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password123!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  app:
    build: .
    container_name: backend_app
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=db;Database=EcommerceDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;"
      JWT__Key: "super-secret-key-at-least-32-bytes-long-required"
      JWT__ExpiresInHours: "1"
    depends_on:
      - db

volumes:
  mssql_data:
